language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t vayalankatil/docker-react -f Dockerfile.Dev .

script:
  - docker run -e CI=true vayalankatil/docker-react npm run test
  
notifications:
  email:
   recipients:
     - sudheeshvayalankatil@gmail.com
   on_success: always
   on_failure: always 
