language: node_js
sudo: required

services:
  - docker

before_install:
  - docker build -t SudheeshKrishnan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true SudheeshKrishnan/docker-react npm run test
